### ISSUE TITLE
error occurs when retrieving from a different corpus when using a customized tokenizer

### ISSUE THREAD

**Issue by mossbee** [xhluca/bm25s#91]
When I used a customized tokenizer, the  vocab is saved by retriever into vocab.index.json under the format of, for example:

{"0": 0, "1": 1, "2": 2, "3": 3, "4": 4, "5": 5, "6": 6, "7": 7, "8": 8, "9": 9, "10": 10, "11": 11}

when i retrieve by ids of query tokens like `results, scores = reloaded_retriever.retrieve(query_tokens, corpus=titles, k=2)` it led to an error when we query in a different corpus

 File "env\Lib\site-packages\bm25s\__init__.py", line 486, in get_scores_from_ids
    raise ValueError(
ValueError: The maximum token ID in the query (12) is higher than the number of tokens in the index.This likely means that the query contains tokens that are not in the index.

In function retrieve of class BM25 in bm25s\__init__.py, the retriever load the vocab this way:

```python
        # if it's a list of list of tokens ids (int), we remove any integer not in the vocab_dict
        if is_list_of_list_of_type(query_tokens, type_=int):
            query_tokens_filtered = []
            for query in query_tokens:
                query_filtered = [
                    token_id for token_id in query if token_id in self.vocab_dict
                ]
                if len(query_filtered) == 0:
                    if "" not in self.vocab_dict:
                        self.vocab_dict[""] = max(self.vocab_dict.values()) + 1
                    query_filtered = [self.vocab_dict[""]]

                query_tokens_filtered.append(query_filtered)

            query_tokens = query_tokens_filtered
 ```

I think a quick fix is add .values in the query_filtered and it work:
```python
    query_filtered = [
        token_id for token_id in query if token_id in self.vocab_dict.values()
    ]
```

Is this correct?

**Comment by xhluca** [comment]
I'm concerned by the time complexity of `in self.vocab_dict.values()`, which is O(N), vs calling `in self.vocab_dict` which is O(1). This should definitely be addressed in the PR.

You also mention that's an issue with the custom tokenizer. What's the default tokenizer's output? Can you change your custom tokenizer to match the behavior of the default one?

**Comment by xhluca** [comment]
@mossbee can you let me know if the new release 0.2.7pre1 works for you? I made substantial changes in #96, and want to make sure there's no side effect and regression before releasing officially as 0.2.7.

**Comment by mossbee** [comment]
Sorry for late reply, I didn't received the notification. Your latest changes still not worked. Maybe you misunderstood my issue, let me clear it out. I wanted to use a customize tokenizer to tokenize my corpus, then index it and retrieve with a different corpus than the original corpus. Here is the full source code to reproduce the issue:

Indexing:
```python
import re
import bm25s
import pickle
import string
import concurrent
import pandas as pd
from pyvi import ViTokenizer
from bm25_utils import all_in_one
from bm25s.tokenization import Tokenizer, Tokenized

# stopwords.csv can be found here: https://drive.google.com/drive/folders/1p9CGiHDCoeDKMeRp_hkwofzVsJqiEtXJ?usp=sharing
filename = "stopwords.csv"
data = pd.read_csv(filename, sep="\t", encoding='utf-8')
list_stopwords = data['stopwords'].tolist()

def clean_text(text):
    text = re.sub('<.*?>', '', text).strip()
    text = re.sub('(\s)+', r'\1', text)
    text = re.sub(r'[0-9]+', '', text)
    # replace '\n' with ' '
    text = text.replace('\n',' ')
    text = text.replace('\"', '')
    return text

def normalize_text(text):
    listpunctuation = string.punctuation.replace('_', '')
    for i in listpunctuation:
        text = text.replace(i, ' ')
    return text.lower()

def word_segment(sent):
    sent = ViTokenizer.tokenize(sent.encode('utf-8').decode('utf-8'))
    return sent

def word_splitter(sentence: str):
    sentence = ViTokenizer.tokenize(sentence.encode('utf-8').decode('utf-8')).split()
    return sentence

def remove_stopword(text):
    pre_text = []
    words = text.split()
    for word in words:
        if word not in list_stopwords:
            pre_text.append(word)
    text2 = ' '.join(pre_text)
    return text2

def all_in_one(content: str):
    return remove_stopword(normalize_text(word_segment(clean_text(content))))

# corpus_list.pkl can be found here: https://drive.google.com/drive/folders/1p9CGiHDCoeDKMeRp_hkwofzVsJqiEtXJ?usp=sharing
corpus = pickle.load(open("corpus_list.pkl", "rb"))
# shrink down corpus size for testing
corpus = corpus[:100]

with concurrent.futures.ThreadPoolExecutor() as executor:
    corpus = list(executor.map(all_in_one, corpus))

tokenizer = Tokenizer(stemmer=None, stopwords=None, splitter=lambda x: x.split())
corpus_tokens = tokenizer.tokenize(corpus)
tokenized = Tokenized(ids=corpus_tokens, vocab=tokenizer.get_vocab_dict())

retriever = bm25s.BM25()
retriever.index(tokenized)

retriever.save("authority_index_bm25_vietnam")
tokenizer.save_vocab(save_dir="authority_index_bm25_vietnam")
```

Retrieval:
```python
import bm25s
from bm25s.tokenization import Tokenizer
from bm25_utils import all_in_one

reloaded_retriever = bm25s.BM25.load("authority_index_bm25_vietnam", load_corpus=False)

tokenizer = Tokenizer(stemmer=None, stopwords=None, splitter=lambda x: x.split())
tokenizer.load_vocab("authority_index_bm25_vietnam")

query = ["loài nào biết bay"]
query = [all_in_one(q) for q in query]

query_tokens = tokenizer.tokenize(query, update_vocab=False)

# anthor corpus for retrieval
titles = [
    "mèo là loài động vật thuộc họ mèo và thích rên",
    "chó là bạn thân nhất của người và thích chơi",
    "chim là loài động vật đẹp đẽ và biết bay",
    "cá là loài sống trong nước và biết bơi",
]
titles = [all_in_one(title) for title in titles]
print(titles)
titles_tokens = tokenizer.tokenize(titles, update_vocab=False)
print(titles_tokens)

results, scores = reloaded_retriever.retrieve(query_tokens, corpus=titles, k=2)

for i in range(results.shape[1]):
    doc, score = results[0, i], scores[0, i]
    print(f"Rank {i+1} (score: {score:.2f}): {doc}")
```

Is my method the right way to use a customize tokenizer and retrieve from a different corpus? @xhluca

**Comment by xhluca** [comment]
What is bm25_util?

**Comment by mossbee** [comment]
> What is bm25_util?

A little mistake, I edited the code.

**Comment by xhluca** [comment]
I ran your code and found an issue with reloading. I have fixed the issue.

Moreover, I identified an issue with your code. instead of:

```bash
results, scores = reloaded_retriever.retrieve(query_tokens, corpus=titles, k=2)
```

you should use:

```
corpus = pickle.load(open("corpus_list.pkl", "rb"))
# shrink down corpus size for testing
original_corpus = corpus[:100]

results, scores = reloaded_retriever.retrieve(query_tokens, corpus=original_corpus, k=2)
```

Since the titles you used in part 2 doesn't have the same length as the original corpus it triggers an error, as the index is built on the 100 docs in the `corpus` whreas in the part 2 you are passing titles that have fewer than 100 docs.

**Comment by xhluca** [comment]
Here's the commit that fixes the error and add a working version of the code you shared above: https://github.com/xhluca/bm25s/commit/fd6abfc8887888fe4cd770ec1502baefa7ed6697

**Comment by mossbee** [comment]
> I ran your code and found an issue with reloading. I have fixed the issue.
> 
> Moreover, I identified an issue with your code. instead of:
> 
> ```shell
> results, scores = reloaded_retriever.retrieve(query_tokens, corpus=titles, k=2)
> ```
> 
> you should use:
> 
> ```
> corpus = pickle.load(open("corpus_list.pkl", "rb"))
> # shrink down corpus size for testing
> original_corpus = corpus[:100]
> 
> results, scores = reloaded_retriever.retrieve(query_tokens, corpus=original_corpus, k=2)
> ```
> 
> Since the titles you used in part 2 doesn't have the same length as the original corpus it triggers an error, as the index is built on the 100 docs in the `corpus` whreas in the part 2 you are passing titles that have fewer than 100 docs.

isn't in this new code we retrieve from the original corpus instead of a new corpus? I found in your README that BM25s support retrieving from a new corpus. Or I should modify the new corpus to have the same length as the original corpus?

**Comment by xhluca** [comment]
yes, the new corpus has to be the same length

**Comment by xhluca** [comment]
@mossbee i think the solution has been found and 0.2.7pre2 introduces some fixes for some of the issues faced. so closing this issue now.

**Comment by mossbee** [comment]
> @mossbee i think the solution has been found and 0.2.7pre2 introduces some fixes for some of the issues faced. so closing this issue now.

Thanks a lot
